/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "calculadora.h"

bool_t
xdr_v (XDR *xdrs, v *objp)
{
	register int32_t *buf;

	 if (!xdr_pointer (xdrs, (char **)objp, sizeof (struct mivector), (xdrproc_t) xdr_mivector))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_mivector (XDR *xdrs, mivector *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->a))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->b))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->c))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_suma_1_argument (XDR *xdrs, suma_1_argument *objp)
{
	 if (!xdr_int (xdrs, &objp->arg1))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->arg2))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_resta_1_argument (XDR *xdrs, resta_1_argument *objp)
{
	 if (!xdr_int (xdrs, &objp->arg1))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->arg2))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_multiplicacion_1_argument (XDR *xdrs, multiplicacion_1_argument *objp)
{
	 if (!xdr_int (xdrs, &objp->arg1))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->arg2))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_division_1_argument (XDR *xdrs, division_1_argument *objp)
{
	 if (!xdr_int (xdrs, &objp->arg1))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->arg2))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_sumavectores_1_argument (XDR *xdrs, sumavectores_1_argument *objp)
{
	 if (!xdr_mivector (xdrs, &objp->arg1))
		 return FALSE;
	 if (!xdr_mivector (xdrs, &objp->arg2))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_restavectores_1_argument (XDR *xdrs, restavectores_1_argument *objp)
{
	 if (!xdr_mivector (xdrs, &objp->arg1))
		 return FALSE;
	 if (!xdr_mivector (xdrs, &objp->arg2))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_multiplicacionescalar_1_argument (XDR *xdrs, multiplicacionescalar_1_argument *objp)
{
	 if (!xdr_mivector (xdrs, &objp->arg1))
		 return FALSE;
	 if (!xdr_mivector (xdrs, &objp->arg2))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_multiplicacionvectorial_1_argument (XDR *xdrs, multiplicacionvectorial_1_argument *objp)
{
	 if (!xdr_mivector (xdrs, &objp->arg1))
		 return FALSE;
	 if (!xdr_mivector (xdrs, &objp->arg2))
		 return FALSE;
	return TRUE;
}
