/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "calculadora.h"

int *
suma_1_svc(int arg1, int arg2,  struct svc_req *rqstp)
{
	static int  result;

	result = arg1 + arg2;

	return &result;
}

int *
resta_1_svc(int arg1, int arg2,  struct svc_req *rqstp)
{
	static int  result;

	result = arg1 - arg2;

	return &result;
}

int *
multiplicacion_1_svc(int arg1, int arg2,  struct svc_req *rqstp)
{
	static int  result;

	result = arg1 * arg2;

	return &result;
}

int *
division_1_svc(int arg1, int arg2,  struct svc_req *rqstp)
{
	static int  result;
	result = 0;
	if(arg2 !=0){
	result = arg1 / arg2;
}

	return &result;
}

mivector *
sumavectores_1_svc(mivector arg1, mivector arg2,  struct svc_req *rqstp)
{
	static mivector  result;

	result.a = arg1.a + arg2.a;
	result.b = arg1.b + arg2.b;

	return &result;
}

mivector *
restavectores_1_svc(mivector arg1, mivector arg2,  struct svc_req *rqstp)
{
	static mivector  result;

	result.a = arg1.a - arg2.a;
	result.b = arg1.b - arg2.b;

	return &result;
}

mivector *
multiplicacionvectores_1_svc(mivector arg1, mivector arg2,  struct svc_req *rqstp)
{
	static mivector  result;

	result.a = arg1.a * arg2.a;
	result.b = arg1.b * arg2.b;

	return &result;
}

mivector *
divisionvectore_1_svc(mivector arg1, mivector arg2,  struct svc_req *rqstp)
{
	static mivector  result;
	if (arg2.a != 0 && arg2.b != 0)
	{
		result.a = arg1.a / arg2.a;
		result.b = arg1.b / arg2.b;
	}else{
		result.a = 0;
		result.b = 0;
	}
		
	
	
	return &result;
}
