/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _CALCULADORA_H_RPCGEN
#define _CALCULADORA_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


typedef struct mivector *v;

struct mivector {
	int a;
	int b;
	int c;
};
typedef struct mivector mivector;

struct suma_1_argument {
	int arg1;
	int arg2;
};
typedef struct suma_1_argument suma_1_argument;

struct resta_1_argument {
	int arg1;
	int arg2;
};
typedef struct resta_1_argument resta_1_argument;

struct multiplicacion_1_argument {
	int arg1;
	int arg2;
};
typedef struct multiplicacion_1_argument multiplicacion_1_argument;

struct division_1_argument {
	int arg1;
	int arg2;
};
typedef struct division_1_argument division_1_argument;

struct sumavectores_1_argument {
	mivector arg1;
	mivector arg2;
};
typedef struct sumavectores_1_argument sumavectores_1_argument;

struct restavectores_1_argument {
	mivector arg1;
	mivector arg2;
};
typedef struct restavectores_1_argument restavectores_1_argument;

struct multiplicacionescalar_1_argument {
	mivector arg1;
	mivector arg2;
};
typedef struct multiplicacionescalar_1_argument multiplicacionescalar_1_argument;

struct multiplicacionvectorial_1_argument {
	mivector arg1;
	mivector arg2;
};
typedef struct multiplicacionvectorial_1_argument multiplicacionvectorial_1_argument;

#define CALCPROG 0x20000001
#define CALCVER 1

#if defined(__STDC__) || defined(__cplusplus)
#define suma 1
extern  int * suma_1(int , int , CLIENT *);
extern  int * suma_1_svc(int , int , struct svc_req *);
#define resta 2
extern  int * resta_1(int , int , CLIENT *);
extern  int * resta_1_svc(int , int , struct svc_req *);
#define multiplicacion 3
extern  int * multiplicacion_1(int , int , CLIENT *);
extern  int * multiplicacion_1_svc(int , int , struct svc_req *);
#define division 4
extern  int * division_1(int , int , CLIENT *);
extern  int * division_1_svc(int , int , struct svc_req *);
#define sumavectores 5
extern  mivector * sumavectores_1(mivector , mivector , CLIENT *);
extern  mivector * sumavectores_1_svc(mivector , mivector , struct svc_req *);
#define restavectores 6
extern  mivector * restavectores_1(mivector , mivector , CLIENT *);
extern  mivector * restavectores_1_svc(mivector , mivector , struct svc_req *);
#define multiplicacionescalar 7
extern  int * multiplicacionescalar_1(mivector , mivector , CLIENT *);
extern  int * multiplicacionescalar_1_svc(mivector , mivector , struct svc_req *);
#define multiplicacionvectorial 8
extern  mivector * multiplicacionvectorial_1(mivector , mivector , CLIENT *);
extern  mivector * multiplicacionvectorial_1_svc(mivector , mivector , struct svc_req *);
extern int calcprog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define suma 1
extern  int * suma_1();
extern  int * suma_1_svc();
#define resta 2
extern  int * resta_1();
extern  int * resta_1_svc();
#define multiplicacion 3
extern  int * multiplicacion_1();
extern  int * multiplicacion_1_svc();
#define division 4
extern  int * division_1();
extern  int * division_1_svc();
#define sumavectores 5
extern  mivector * sumavectores_1();
extern  mivector * sumavectores_1_svc();
#define restavectores 6
extern  mivector * restavectores_1();
extern  mivector * restavectores_1_svc();
#define multiplicacionescalar 7
extern  int * multiplicacionescalar_1();
extern  int * multiplicacionescalar_1_svc();
#define multiplicacionvectorial 8
extern  mivector * multiplicacionvectorial_1();
extern  mivector * multiplicacionvectorial_1_svc();
extern int calcprog_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_v (XDR *, v*);
extern  bool_t xdr_mivector (XDR *, mivector*);
extern  bool_t xdr_suma_1_argument (XDR *, suma_1_argument*);
extern  bool_t xdr_resta_1_argument (XDR *, resta_1_argument*);
extern  bool_t xdr_multiplicacion_1_argument (XDR *, multiplicacion_1_argument*);
extern  bool_t xdr_division_1_argument (XDR *, division_1_argument*);
extern  bool_t xdr_sumavectores_1_argument (XDR *, sumavectores_1_argument*);
extern  bool_t xdr_restavectores_1_argument (XDR *, restavectores_1_argument*);
extern  bool_t xdr_multiplicacionescalar_1_argument (XDR *, multiplicacionescalar_1_argument*);
extern  bool_t xdr_multiplicacionvectorial_1_argument (XDR *, multiplicacionvectorial_1_argument*);

#else /* K&R C */
extern bool_t xdr_v ();
extern bool_t xdr_mivector ();
extern bool_t xdr_suma_1_argument ();
extern bool_t xdr_resta_1_argument ();
extern bool_t xdr_multiplicacion_1_argument ();
extern bool_t xdr_division_1_argument ();
extern bool_t xdr_sumavectores_1_argument ();
extern bool_t xdr_restavectores_1_argument ();
extern bool_t xdr_multiplicacionescalar_1_argument ();
extern bool_t xdr_multiplicacionvectorial_1_argument ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_CALCULADORA_H_RPCGEN */
