/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "calculadora.h"
#include <stdio.h>
#include <stdlib.h>
#include <rpc/pmap_clnt.h>
#include <string.h>
#include <memory.h>
#include <sys/socket.h>
#include <netinet/in.h>

#ifndef SIG_PF
#define SIG_PF void(*)(int)
#endif

static int *
_suma_1 (suma_1_argument *argp, struct svc_req *rqstp)
{
	return (suma_1_svc(argp->arg1, argp->arg2, rqstp));
}

static int *
_resta_1 (resta_1_argument *argp, struct svc_req *rqstp)
{
	return (resta_1_svc(argp->arg1, argp->arg2, rqstp));
}

static int *
_multiplicacion_1 (multiplicacion_1_argument *argp, struct svc_req *rqstp)
{
	return (multiplicacion_1_svc(argp->arg1, argp->arg2, rqstp));
}

static int *
_division_1 (division_1_argument *argp, struct svc_req *rqstp)
{
	return (division_1_svc(argp->arg1, argp->arg2, rqstp));
}

static mivector *
_sumavectores_1 (sumavectores_1_argument *argp, struct svc_req *rqstp)
{
	return (sumavectores_1_svc(argp->arg1, argp->arg2, rqstp));
}

static mivector *
_restavectores_1 (restavectores_1_argument *argp, struct svc_req *rqstp)
{
	return (restavectores_1_svc(argp->arg1, argp->arg2, rqstp));
}

static int *
_multiplicacionescalar_1 (multiplicacionescalar_1_argument *argp, struct svc_req *rqstp)
{
	return (multiplicacionescalar_1_svc(argp->arg1, argp->arg2, rqstp));
}

static mivector *
_multiplicacionvectorial_1 (multiplicacionvectorial_1_argument *argp, struct svc_req *rqstp)
{
	return (multiplicacionvectorial_1_svc(argp->arg1, argp->arg2, rqstp));
}

static void
calcprog_1(struct svc_req *rqstp, register SVCXPRT *transp)
{
	union {
		suma_1_argument suma_1_arg;
		resta_1_argument resta_1_arg;
		multiplicacion_1_argument multiplicacion_1_arg;
		division_1_argument division_1_arg;
		sumavectores_1_argument sumavectores_1_arg;
		restavectores_1_argument restavectores_1_arg;
		multiplicacionescalar_1_argument multiplicacionescalar_1_arg;
		multiplicacionvectorial_1_argument multiplicacionvectorial_1_arg;
	} argument;
	char *result;
	xdrproc_t _xdr_argument, _xdr_result;
	char *(*local)(char *, struct svc_req *);

	switch (rqstp->rq_proc) {
	case NULLPROC:
		(void) svc_sendreply (transp, (xdrproc_t) xdr_void, (char *)NULL);
		return;

	case suma:
		_xdr_argument = (xdrproc_t) xdr_suma_1_argument;
		_xdr_result = (xdrproc_t) xdr_int;
		local = (char *(*)(char *, struct svc_req *)) _suma_1;
		break;

	case resta:
		_xdr_argument = (xdrproc_t) xdr_resta_1_argument;
		_xdr_result = (xdrproc_t) xdr_int;
		local = (char *(*)(char *, struct svc_req *)) _resta_1;
		break;

	case multiplicacion:
		_xdr_argument = (xdrproc_t) xdr_multiplicacion_1_argument;
		_xdr_result = (xdrproc_t) xdr_int;
		local = (char *(*)(char *, struct svc_req *)) _multiplicacion_1;
		break;

	case division:
		_xdr_argument = (xdrproc_t) xdr_division_1_argument;
		_xdr_result = (xdrproc_t) xdr_int;
		local = (char *(*)(char *, struct svc_req *)) _division_1;
		break;

	case sumavectores:
		_xdr_argument = (xdrproc_t) xdr_sumavectores_1_argument;
		_xdr_result = (xdrproc_t) xdr_mivector;
		local = (char *(*)(char *, struct svc_req *)) _sumavectores_1;
		break;

	case restavectores:
		_xdr_argument = (xdrproc_t) xdr_restavectores_1_argument;
		_xdr_result = (xdrproc_t) xdr_mivector;
		local = (char *(*)(char *, struct svc_req *)) _restavectores_1;
		break;

	case multiplicacionescalar:
		_xdr_argument = (xdrproc_t) xdr_multiplicacionescalar_1_argument;
		_xdr_result = (xdrproc_t) xdr_int;
		local = (char *(*)(char *, struct svc_req *)) _multiplicacionescalar_1;
		break;

	case multiplicacionvectorial:
		_xdr_argument = (xdrproc_t) xdr_multiplicacionvectorial_1_argument;
		_xdr_result = (xdrproc_t) xdr_mivector;
		local = (char *(*)(char *, struct svc_req *)) _multiplicacionvectorial_1;
		break;

	default:
		svcerr_noproc (transp);
		return;
	}
	memset ((char *)&argument, 0, sizeof (argument));
	if (!svc_getargs (transp, (xdrproc_t) _xdr_argument, (caddr_t) &argument)) {
		svcerr_decode (transp);
		return;
	}
	result = (*local)((char *)&argument, rqstp);
	if (result != NULL && !svc_sendreply(transp, (xdrproc_t) _xdr_result, result)) {
		svcerr_systemerr (transp);
	}
	if (!svc_freeargs (transp, (xdrproc_t) _xdr_argument, (caddr_t) &argument)) {
		fprintf (stderr, "%s", "unable to free arguments");
		exit (1);
	}
	return;
}

int
main (int argc, char **argv)
{
	register SVCXPRT *transp;

	pmap_unset (CALCPROG, CALCVER);

	transp = svcudp_create(RPC_ANYSOCK);
	if (transp == NULL) {
		fprintf (stderr, "%s", "cannot create udp service.");
		exit(1);
	}
	if (!svc_register(transp, CALCPROG, CALCVER, calcprog_1, IPPROTO_UDP)) {
		fprintf (stderr, "%s", "unable to register (CALCPROG, CALCVER, udp).");
		exit(1);
	}

	transp = svctcp_create(RPC_ANYSOCK, 0, 0);
	if (transp == NULL) {
		fprintf (stderr, "%s", "cannot create tcp service.");
		exit(1);
	}
	if (!svc_register(transp, CALCPROG, CALCVER, calcprog_1, IPPROTO_TCP)) {
		fprintf (stderr, "%s", "unable to register (CALCPROG, CALCVER, tcp).");
		exit(1);
	}

	svc_run ();
	fprintf (stderr, "%s", "svc_run returned");
	exit (1);
	/* NOTREACHED */
}
